set(__QT_DEPLOY_TARGET_projects_flameon_FILE /Users/chinchillacrazy/Code/Graphics/proj-flameon/projects_flameon)
set(__QT_DEPLOY_TARGET_projects_flameon_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_StaticGLEW_FILE /Users/chinchillacrazy/Code/Graphics/proj-flameon/libStaticGLEW.a)
set(__QT_DEPLOY_TARGET_StaticGLEW_TYPE STATIC_LIBRARY)
